version: 2
jobs:
    build:
        docker:
            - image: circleci/node:8.12

        steps:
            - checkout

            - restore_cache:
                  keys:
                      - v1-{{ checksum "frontend/package.json" }}

            - run:
                  name: Install Package
                  command: |
                      cd frontend
                      yarn
            - save_cache:
                  paths:
                      - frontend/node_modules
                  key: v1-{{ checksum "frontend/package.json" }}

            - run:
                  name: Build
                  command: |
                      cd frontend
                      yarn run generate
            - persist_to_workspace:
                  root: .
                  paths:
                      - .

    deploy:
        docker:
            - image: cdssnc/aws-cli

        steps:
            - checkout

            - attach_workspace: # workspaceをアタッチする
                  at: .

            - run:
                  name: Deploy to S3
                  command: |
                      cd frontend
                      mkdir -p dist
                      ./deploy_to_s3.sh
workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - deploy: # deployはbuildのあとに実行
                  requires:
                      - build
                  filters: # developブランチの場合のみデプロイする
                      branches:
                          only: master
