version: 2
jobs:
    build:
        docker:
            - image: circleci/node:8.12

        steps:
            - checkout

            - restore_cache:
                  keys:
                      - v1-{{ checksum "frontend/package.json" }}

            - run:
                  name: Install Package
                  command: |
                      cd frontend
                      yarn

            - save_cache:
                  paths:
                      - frontend/node_modules
                  key: v1-{{ checksum "frontend/package.json" }}

            - run:
                  name: Build
                  command: |
                      cd frontend
                      yarn run generate

            - persist_to_workspace:
                  root: .
                  paths:
                      - .

    deploy-frontend:
        docker:
            - image: cdssnc/aws-cli

        steps:
            - checkout

            - attach_workspace:
                  at: .

            - deploy:
                  name: Deploy web page
                  command: |
                      cd frontend
                      mkdir -p dist
                      ./deploy_to_s3.sh

    deploy-serverless:
        docker:
            - image: shinsukeabe/circleci-serverless-python3

        steps:
            - checkout

            - run:
                  name: Deploy lambda function
                  command: |
                      cd lambda
                      npm install --save serverless-python-requirements serverless-prune-plugin
                      serverless deploy -v
workflows:
    version: 2
    build-deploy:
        jobs:
            - build

            - deploy-frontend:
                  requires:
                      - build
                  filters:
                      branches:
                          only: master

            - deploy-serverless:
                  requires:
                      - build
                  # filters:
                  #     branches:
                  #         only: master
